image:
  repository: "k3d-registry.localhost:5000/tezos-api-gateway"

rabbitmq:
  ingress:
    hostname: rabbitmq.tezos-api-gateway.localhost
    annotations:
      cert-manager.io/common-name: rabbitmq.tezos-api-gateway.localhost
  auth:
    tls:
      existingSecret: rabbitmq.tezos-api-gateway.localhost-tls
      sslOptionsVerify: verify_none

vault:
  server:
    dev:
      enabled: true
      devRootToken: myroot

api:
  ingress:
    annotations:
      cert-manager.io/common-name: tezos-api-gateway.localhost
    hosts:
      - host: tezos-api-gateway.localhost
        paths:
          - path: "/"
    tls:
      - secretName: tezos-api-gateway.localhost-tls
        hosts:
          - tezos-api-gateway.localhost

  vault:
    server:
      dev:
        devRootToken: myroot

checkOperationStatusWorker:
  vault:
    server:
      dev:
        devRootToken: myroot

sendTransactionsWorker:
  vault:
    server:
      dev:
        devRootToken: myroot
