api:
  ingress:
    enabled: true
    certManager: true
    annotations:
      kubernetes.io/tls-acme: "true"

generatedApi:
  ingress:
    enabled: false
    certManager: true
    annotations:
      kubernetes.io/tls-acme: "true"

rabbitmq:
  name: rabbitmq
  service:
    type: LoadBalancer
  ingress:
    enabled: true
    certManager: true
    tls: true
  resources:
    requests:
      cpu: 500m
      memory: 300Mi
