version: '2.2'
services:
  postgres:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_DB=tezos_api_gateway
      - POSTGRES_USER=tezos-service
      - POSTGRES_PASSWORD=randompwd
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  vault:
    image: registry.gitlab.com/the-blockchain-xdev/xdev-product/enterprise-business-network/vault:master
    restart: always
    ports:
      - "8300:8200"
    environment:
      - VAULT_DEBUG=true
      - VAULT_ADDR='http://127.0.0.1:8200'
      - VAULT_APP_TOKEN=myroot
      - VAULT_SEAL_TYPE
      - GOOGLE_PROJECT
      - GOOGLE_REGION=global
      - VAULT_GCPCKMS_SEAL_KEY_RING
      - VAULT_GCPCKMS_SEAL_CRYPTO_KEY=unseal
      - VAULT_INIT_PATH
      - VAULT_INIT_TOKEN
    volumes:
      - vault:/vault/file
    cap_add:
      - IPC_LOCK
volumes:
  postgres:
  vault:
