version: '3'

services:
  postgres:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_DB=tezos_api_gateway_test
      - POSTGRES_USER=tezos-service
      - POSTGRES_PASSWORD=randompwd
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - '127.0.0.1:5672:5672'

volumes:
  postgres:
