version: '2.2'
services:
  postgres:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_DB=tezos_api_gateway_test
      - POSTGRES_USER=tezos-service
      - POSTGRES_PASSWORD=randompwd
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  postgres:
