import { Pool } from 'pg';

import { PostgreConfig } from '../const/interfaces/postgre-config';
import { postgreConfig } from '../config';
import { PostgreTypes } from '../const/postgre/postgre-types';
import { PostgreTables } from '../const/postgre/postgre-tables';
import { OpKind } from '@taquito/rpc';

export class PostgreService {
  private _pool: Pool;
  private _config: PostgreConfig;

  constructor(config: PostgreConfig = postgreConfig) {
    this._config = config;
    this._pool = new Pool(this._config);
  }

  public get pool() {
    return this._pool;
  }

  public get config() {
    return this._config;
  }

  public async disconnect() {
    await this._pool.end();
  }

  public async initializeDatabase() {
    if (!(await this.checkIfTypeExist(PostgreTypes.JOB_STATUS))) {
      await this._pool.query(
        `CREATE TYPE job_status AS ENUM ('created', 'published', 'done', 'error')`,
      );
    }

    await this._pool.query(`CREATE TABLE IF NOT EXISTS ${PostgreTables.JOBS} (
        id INT GENERATED BY DEFAULT AS IDENTITY,
        status job_status NOT NULL,
        raw_transaction TEXT,
        operation_hash TEXT,
        error_message TEXT,
        PRIMARY KEY (id)
      )`);

    await this._pool.query(`
        ALTER TABLE IF EXISTS transaction RENAME TO ${PostgreTables.OPERATIONS};`);

    await this._pool
      .query(`CREATE TABLE IF NOT EXISTS ${PostgreTables.OPERATIONS} (
        id INT GENERATED BY DEFAULT AS IDENTITY,
        job_id INT NOT NULL,
        destination TEXT NOT NULL,
        source TEXT NOT NULL,
        parameters TEXT,
        parameters_json TEXT,
        amount INT,
        fee INT,
        storage_limit INT,
        gas_limit INT,
        counter INT,
        branch TEXT,
        PRIMARY KEY (id),
        CONSTRAINT fk_job
            FOREIGN KEY(job_id) 
            REFERENCES jobs(id)
      )`);

    await this._pool.query(`
        ALTER TABLE ${PostgreTables.OPERATIONS} ADD COLUMN IF NOT EXISTS caller_id VARCHAR(100);
        ALTER TABLE ${PostgreTables.OPERATIONS} ADD COLUMN IF NOT EXISTS kind VARCHAR(100);
        ALTER TABLE ${PostgreTables.OPERATIONS} ADD COLUMN IF NOT EXISTS public_key TEXT;
        UPDATE ${PostgreTables.OPERATIONS} SET kind = '${OpKind.TRANSACTION}' WHERE kind IS NULL;
        ALTER TABLE ${PostgreTables.OPERATIONS} ADD COLUMN IF NOT EXISTS creation_date VARCHAR(100);
        ALTER TABLE ${PostgreTables.OPERATIONS} ADD COLUMN IF NOT EXISTS update_date VARCHAR(100);
        ALTER TABLE ${PostgreTables.JOBS} ADD COLUMN IF NOT EXISTS operation_kind TEXT;
      `);

    // IF EXIST to rename a column isn't supported by PostgreSQL, we have to do it manually
    // See https://www.codingvila.com/2021/05/rename-column-only-if-exists-in-postgresql.html
    const result = await this._pool.query(`
        SELECT * FROM information_schema.columns WHERE table_name='${PostgreTables.JOBS}' and column_name='raw_transaction'`);

    if (result.rows.length === 1) {
      await this._pool.query(`
        ALTER TABLE ${PostgreTables.JOBS} RENAME COLUMN raw_transaction TO forged_operation;
        UPDATE ${PostgreTables.JOBS} SET operation_kind = '${OpKind.TRANSACTION}' WHERE operation_kind IS NULL;
      `);
    }
  }

  private async checkIfTypeExist(typeName: string) {
    const result = await this._pool.query(
      `SELECT typname FROM pg_type WHERE typname = '${typeName}'`,
    );

    return result.rows.length > 0;
  }
}
