apiVersion: v1
kind: Service
metadata:
  name: {{ include "tezos-api-gateway-send-transactions-worker.fullname" . }}
  labels:
    {{- include "tezos-api-gateway-send-transactions-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9466
      protocol: TCP
      name: http
  selector:
    {{- include "tezos-api-gateway-send-transactions-worker.selectorLabels" . | nindent 4 }}
