apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tezos-api-gateway.fullname" . }}-api
  labels:
    {{- include "tezos-api-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tezos-api-gateway.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tezos-api-gateway.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: tezos-api-gateway-api
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_USERNAME
              value: {{ .Values.api.postgresql.postgresqlUsername | quote }}
            - name: DB_NAME
              value: {{ .Values.api.postgresql.postgresqlDatabase | quote }}
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-{{ .Values.api.postgresql.name }}"
                  key: postgresql-password
            - name: DB_HOST
              value: "{{ .Release.Name }}-{{ .Values.api.postgresql.name }}"
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-{{ .Values.api.rabbitmq.name }}"
                  key: rabbitmq-password
            - name: AMQP_URL
              value: "amqp://user:$(AMQP_PASSWORD)@{{ .Release.Name }}-{{ .Values.api.rabbitmq.name }}"
            - name: VAULT_URL
              value: "http://{{ .Release.Name }}-{{ .Values.api.vault.name }}:{{ .Values.api.vault.port }}/v1/"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-{{ .Values.api.vault.name }}"
                  key: vault-app-token
          ports:
            - name: http
              containerPort: 3333
              protocol: TCP
            - name: prometheus
              containerPort: 9464
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: prometheus
          readinessProbe:
            httpGet:
              path: /metrics
              port: prometheus
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
