{{- if .Values.injectionWorker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tezos-api-gateway.fullname" . }}-injection-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tezos-api-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: injection-worker
spec:
  type: {{ .Values.injectionWorker.service.type }}
  {{- if .Values.injectionWorker.metrics.enabled }}
  ports:
    - port: {{ .Values.injectionWorker.service.port }}
      targetPort: 9466
      protocol: TCP
      name: prometheus
  {{- end }}
  selector:
    {{- include "tezos-api-gateway.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: injection-worker
{{- end }}
