{{- if .Values.sendTransactionsWorker.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tezos-api-gateway-send-transactions-worker
  labels:
    {{- include "tezos-api-gateway.labels" . | nindent 4 }}
  {{- with .Values.sendTransactionsWorker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
