{{- if .Values.sendTransactionsWorker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tezos-api-gateway.fullname" . }}-send-transactions-worker
  labels:
    {{- include "tezos-api-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: send-transactions-worker
spec:
  type: {{ .Values.sendTransactionsWorker.service.type }}
  {{- if .Values.sendTransactionsWorker.metrics.enabled }}
  ports:
    - port: {{ .Values.sendTransactionsWorker.service.port }}
      targetPort: 9466
      protocol: TCP
      name: prometheus
  {{- end }}
  selector:
    {{- include "tezos-api-gateway.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: send-transactions-worker
{{- end }}
