{{ $name := (include "tezos-api-gateway.db.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tezos-api-gateway.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "tezos-api-gateway.automaticSecret" (list . $name "password" 20 .Values.db.auth.password) }}
{{- include "tezos-api-gateway.automaticSecret" (list . $name "postgres-password" 20 .Values.db.auth.postgresPassword) }}
