apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tezos-api-gateway.rabbitmq.fullname" . }}
  labels:
    {{- include "tezos-api-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $keys := list "rabbitmq-password" "rabbitmq-erlang-cookie" }}
  {{- include "tezos-api-gateway.automaticSecret" (list . (include "tezos-api-gateway.rabbitmq.fullname" .) $keys) | indent 2 }}
