{{ $name := printf "%s-%s" (include "tezos-api-gateway.fullname" . ) .Values.rabbitmq.nameOverride }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "tezos-api-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $keys := list "rabbitmq-password" "rabbitmq-erlang-cookie" }}
  {{- include "tezos-api-gateway.automaticSecret" (list . $name $keys) | indent 2 }}
