{{ $name := (include "tezos-api-gateway.rabbitmq.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tezos-api-gateway.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "tezos-api-gateway.automaticSecret" (list . $name "rabbitmq-password" 20 .Values.rabbitmq.auth.password) }}
{{- include "tezos-api-gateway.automaticSecret" (list . $name "rabbitmq-erlang-cookie" 20 .Values.rabbitmq.auth.erlangCookie) }}
