apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tezos-api-gateway.vault.fullname" . }}
  labels:
    {{- include "tezos-api-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $keys := list "root-token" }}
  {{- include "tezos-api-gateway.automaticSecret" (list . (include "tezos-api-gateway.vault.fullname" .) $keys) | indent 2 }}
