{{ $name := printf "%s-%s" (include "tezos-api-gateway.vault.fullname" .) "root-token" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tezos-api-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  # {{ .Values.vault.rootToken  }}
{{- include "tezos-api-gateway.automaticSecret" (list . $name "root-token" 20 .Values.vault.rootToken) }}
