{{- if and .Values.generatedApi.enabled .Values.generatedApi.ingress.enabled }}
{{- $fullName := include "tezos-api-gateway.fullname" . -}}
{{- $svcPort := .Values.generatedApi.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-generated-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tezos-api-gateway.labels" . | nindent 4 }}
  {{- with .Values.generatedApi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.generatedApi.ingress.tls }}
  tls:
    {{- range .Values.generatedApi.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.generatedApi.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-generated-api
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
