{{- if .Values.generatedApi.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "tezos-api-gateway.fullname" . }}-generated-api
  labels:
    {{- include "tezos-api-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: generated-api
spec:
  podSelector:
    matchLabels:
      {{- include "tezos-api-gateway.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: generated-api
  ingress:
    - from:
      - podSelector:
          matchLabels:
            {{ include "tezos-api-gateway.fullname" . }}-generated-api-client: "true"
{{- end }}
