{{- if and .Values.generatedApi.enabled .Values.generatedApi.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tezos-api-gateway.fullname" . }}-generated-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tezos-api-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: generated-api
spec:
  selector:
    matchLabels:
      {{- include "tezos-api-gateway.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: generated-api
  endpoints:
    - port: prometheus
      {{- if .Values.generatedApi.metrics.interval }}
      interval: {{ .Values.generatedApi.metrics.interval }}
      {{- end }}
      {{- if .Values.generatedApi.metrics.scrapeTimeout }}
      scrapeTimeout: {{ .Values.generatedApi.metrics.scrapeTimeout }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
