apiVersion: v1
kind: Service
metadata:
  name: {{ include "tezos-api-gateway.fullname" . }}-generated-api
  labels:
    {{- include "tezos-api-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: generated-api
spec:
  type: {{ .Values.generatedApi.service.type }}
  ports:
    - port: {{ .Values.generatedApi.service.port }}
      targetPort: 3333
      protocol: TCP
      name: http
  selector:
    {{- include "tezos-api-gateway.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: generated-api
