{{- if .Values.generatedApi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tezos-api-gateway.fullname" . }}-generated-api
  labels:
    {{- include "tezos-api-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: generated-api
  {{- with .Values.generatedApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
