name: ci
on:
  push:
    branches:
      - "**"

env:
  EARTHLY_REMOTE_CACHE: cache.registry/${{ github.repository }}/${{ github.job }}/${{ github.ref_name }}:cache
  EARTHLY_CACHE_FROM: cache.registry/${{ github.repository }}/${{ github.job }}/develop:cache
  EARTHLY_PUSH: "true"
  EARTHLY_STRICT: "true"

jobs:

  ############################ tests ############################

  test:
    runs-on: [self-hosted]
    steps:
    - uses: eniblock/build/actions/setup@develop
      id: setup
      with:
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Run api tests
      run: |
        earthly --allow-privileged +test

  lint-helm:
    runs-on: [self-hosted]
    steps:
    - uses: eniblock/build/actions/setup@develop
      id: setup
      with:
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: |
        earthly ./helm+lint


  ############################ docker ############################

  docker:
    runs-on: [self-hosted]
    needs: [test, lint-helm]
    steps:
    - uses: eniblock/build/actions/setup@develop
      id: setup
      with:
        helmdir: helm/tezos-api-gateway
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the asset image
      run: |
        earthly --push +docker --tag=${{ steps.setup.outputs.tag }}


  ############################ helm ############################

  helm-publish:
    runs-on: [self-hosted]
    needs: [docker]
    steps:
    - uses: eniblock/build/actions/setup@develop
      id: setup
      with:
        helmdir: helm/tezos-api-gateway
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build/Publish the helm charts
      run: |
        earthly \
          --secret registry_username=notused \
          --secret registry_password=${{ github.token }} \
          ./helm+publish \
          --tag=${{ steps.setup.outputs.tag }}
